AMAZON_ACCESS_KEY = 'AKIAJP6TKUKPNTGCFZCA'
AMAZON_SECRET_KEY = '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'
AMAZON_PARTNER_ID = 'eliatolin03-21'
AMAZON_COUNTRY = 'IT'
DATABASE_HOST = '127.0.0.1'
DATABASE_PORT = 6379
DATABASE_REFRESH_TIME_SECONDS = 3600
