name = "amazon_route"
url_prefix_route = "/pa_amazon"
get_offers_route = "/get_category_offers"
search_products_route = "/search_product"
add_category_preference = "/add_category_preference"
get_products_by_asin = "/get_products_by_asin"
