wrong_type_parameter = "wrong_type_parameter"
empty_results = "empty_results"
error_convert_json = "error_convert_json"
empty_category = "empty_category"
empty_wordlist = "empty_wordlist"
limit_reached_products = "limit_reached_products"
generic_error = "generic_error"
invalid_arguments = "invalid_arguments"
category_not_exist = "category_not_exist"
url_not_definited = "url_not_definited"
missing_parameter = "missing_parameter"
generic_error_amazon = "generic_error_amazon"
too_many_request = "too_many_request"

